// <auto-generated />
namespace FormYonetimi.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AdminForm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdminForm));
        
        string IMigrationMetadata.Id
        {
            get { return "201902142327092_AdminForm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
